### ISSUE TITLE
Use OAuth for authentication

### ISSUE THREAD

**Issue by the-JJ** [nepda/youtrack-client#31]
There should be support for using Hub's OAuth authentication instead of plain username & password

https://www.jetbrains.com/help/hub/2.5/OAuth-2.0-Authorization.html

**Comment by nepda** [comment]
Good idea, I'll look into this as soon as more time is available. Feel free to create a patch and open a pull request ;)

**Comment by sciamannikoo** [comment]
Now that they've introduced permanent tokens, this feature became even more useful.

See https://www.jetbrains.com/help/youtrack/incloud/2017.1/Log-in-to-YouTrack.html

**Comment by the-JJ** [comment]
I made the fork today. Still have to test it a bit, but looks like it's working:
https://github.com/the-JJ/youtrack/tree/permanent-token

**Comment by nepda** [comment]
Nice, thank you! I'll look into it ASAP.

**Comment by the-JJ** [comment]
Great!
I am still not sure how it would behave in case of errors (invalid token, etc), so that has to be checked (and probably some verification implemented).

**Comment by sciamannikoo** [comment]
I've just started using your library and, for now, I'll stick to the standard user/password authentication.

Once I'm done with my work (*) unless you are faster than me, I'll be happy to fork your project and see if I can propose something for this request.

(*) It may take some time, as it's that kind of "side projects" to work on the little spare time

**Comment by nepda** [comment]
This feature will be available in v2. This new version is not compatible with the current v1 branch and I've just startet the development. As soon as a working code-base exists I'll push into branch `v2.0.0-alpha`.

**Comment by nepda** [comment]
I've added the permanent token login in `v1.7.0`. Just read the updated `README.md` for usage information of the new feature.
