### ISSUE TITLE
How to access issue's fields?

### ISSUE THREAD

**Issue by sciamannikoo** [nepda/youtrack-client#33]
Looking at the code, it seems like the `Issue` class stores the issue's fields in a protected `$attributes` property in his base class, using the `__set` magic method.

However, some fields have spaces in their names and I wonder how I'm supposed to get their values.

I've checked all the examples, as well as the code, and... I'm lost :)

**Comment by nepda** [comment]
You can use the `__get` method manually.

    $issue->__get("My nice attribute (with special chars)");

**Comment by sciamannikoo** [comment]
I should have thought about that. Thanks!
