### ISSUE TITLE
Add updateComment function

### ISSUE THREAD

**Issue by DRogue1337** [nepda/youtrack-client#36]
As of this comment: https://youtrack.jetbrains.com/issue/JT-41161#comment=27-2123048

Updating a comment via the REST API is possible. I tried implementing it,

```
public function updateComment($issueId, $commentId, $text)
    {
        $r = $this->request('PUT', '/rest/issue/' .
                                   rawurlencode($issueId) . '/comment/' .
                                   rawurlencode($commentId) .
                                   "?text=$text", '');
        return $r['content'];
    }
```

but it didn't work. So either it's me doing stuff wrong or updating comments is not possible right now.

Could you check this?

**Comment by nepda** [comment]
I've added 2 methods and examples (`create-comment.php` and `update-comment.php`). Please check this out and see if it works for you.
For update comment I receive a 404 error. Don't know if it is miss configuration of YouTrack or wrong implemented.

**Comment by DRogue1337** [comment]
You are getting a 404 because your url is `/rest/rest/`. I'm getting a 405 right now.

I thought it was because I was running version 2017.1, so I upgraded to 2017.2. But still 405.

Maybe a miss configuration, but my user is Project Admin, so I don't know yet.

**Comment by nepda** [comment]
Thank you. Stupid me. Ok, now i get it. It will take a few hours to fix this (I've got some other things to do)

**Comment by nepda** [comment]
@DRogue1337 Can you test this please and tell me, if it works for your setup?

**Comment by DRogue1337** [comment]
It's working now, thanks!
