### ISSUE TITLE
Issues are missing tags

### ISSUE THREAD

**Issue by sciamannikoo** [nepda/youtrack-client#37]
It looks like `\YouTrack\Issue` is completely ignoring tags.

How can I see which tags a given issue contains?

**Comment by nepda** [comment]
With version `v1.6.3` this is fixed in a very simple way. Just check if tags exists:

`if ($issue->__get('tags'))`

Then go through them: 

`foreach ($issue->getTags() as $tag) { echo $tag; }`

**Comment by nepda** [comment]
Please report any problems with this solution. Thanks for reporting this.
