### ISSUE TITLE
createIssue no longer works

### ISSUE THREAD

**Issue by LBreda** [nepda/youtrack-client#39]
createIssue no longer works, it returns a 400 bad request error.

The main problem appears to be it needs to be a PUT request.

Besides, the endpoit does no longer return Issue data: it returns its location in the response headers.

**Comment by nepda** [comment]
What version of YouTrack do you use? I'm currently using the latest youtrack-client version an it works perfectly with YouTrack in Cloud 2017.2, Build 34480 2017-07-06.

**Comment by LBreda** [comment]
Same version, same build. It gave me a 400 bad request error. I had to temporarily patch Connection.php adding a `curl_setopt($this->http, CURLOPT_HEADER, 1);`to `request()` and getting the headers from `createIssue`

```
if (!isset($issue)) {
  $issue_id = array_slice(explode('/', rtrim($headers['Location'], '/')), -1)[0];
  $issue = $this->getIssue($issue_id);
}
return $issue;
```

**Comment by nepda** [comment]
Don't know why it doesn't work for you. I'm using `v1.7.0`.

    php examples/create-simple-issue.php 
    Issue Sandbox-4249 created

with no modification.

Does the example work for you?

Sorry for the inconvenience.

**Comment by LBreda** [comment]
I get a different error type, due to CLI, I suppose:

```
Caught a generic YouTrack exception: Error for 'https://[omissis].myjetbrains.com/youtrack/rest/issue?priority=Higher&type=Auto-reported+CLI+exception&description=The+full+text+issue+description&project=Sandbox&summary=Create+a+basic+issue+for+example': 400: Can't create value from string [ Auto-reported CLI exception] for field [Type ]
object(YouTrack\Error)#5 (2) {
  ["youtrack":protected]=>
  NULL
  ["attributes":protected]=>
  array(1) {
    ["error"]=>
    string(79) "Can't create value from string [ Auto-reported CLI exception] for field [Type ]"
  }
}
```

**Comment by nepda** [comment]
Please try to customize the example to not use not-defined fields or field-values. After this, maybe we find the error reason.

**Comment by LBreda** [comment]
Uhm, it works. I can't see how, since I solved my issue following the official documentation (PUT request and no issue xml in the response), but it works.

I'll try to figure out. Thank you!
