### ISSUE TITLE
importAttachment 204

### ISSUE THREAD

**Issue by umahanov** [nepda/youtrack-client#40]
Hi, all. Trying to import attachment. 

`$this->apiYouTrack->importAttachment($issue->getId(), $authorLogin, $attachment->getFilename(), $file->getContents(), $attachment->getCreatedAt()->getTimestamp());`

Where `$file` is `GuzzleHttp\Psr7\Stream`

Response is 204 No Content.

Nothing attached to issue. Any suggestions?

**Comment by nepda** [comment]
Thanks for your report. It seems like the method you're using is obsolete. Please see `./examples/create-attachment.php` for example.
Please use the preferred way via the method `createAttachmentFromAttachment`.
I'll mark the old method as obsolet in the next version.

**Comment by umahanov** [comment]
Method `createAttachmentFromAttachment` creates attachment from object, where attachment set from `url.` In my case it is not possible, because `url` is secure and is not public. That is why `importAttachment` method is preferred way, which offers to create attachment from resource or loaded in memory file. 

What do I need to do in this situation? Is there any existing alternative?

**Comment by nepda** [comment]
If you're creating a from a local file, you can use `setUrl` with a local file path (like the `example/create-attachment.php`. On creation the `\YouTrack\Connection::request` method will check for `file_exists` with this URL.
I've committed a small improvement for local file paths right now. But it should worked before.

If not, please post a code snipped/gist of your implementation

**Comment by umahanov** [comment]
Actually, the way I prefer is to get file from  url (with token), save it in memory, transfer to youtrack

The way with storing file on local pc will lead to unwanted read/write operations. 

We transfering about 2000 tickets from Assembla to YouTrack. Each ticket have many attachments. It is going to be very long if I'll need to save each file on local and then read it import in YouTrack.

So, as I understand, there is not way to make it work like I mentioned. Am I right?

**Comment by nepda** [comment]
Can you please explain the "Auth" mechanism to retrieve a file from Assembla?
I would suggest something like:
```
$token = 'keuveer5Hooqu3aeshoh0vei8ouNgohc';

foreach ($assembleTickets as $oldTicket) {

    $params = transform_assembla_to_youtrack($oldTicket);
    $issue = $youtrack->createIssue('Assembla-Import', $params['summary'], $params);

    if ($oldTicket->hasAttachments()) {
        foreach ($oldTicket->attachments() as $att) {
            $remoteFile ='https://my-private-assembla.example.com/' . $att['id'] . '?token=' . $token;
            $tmpFile = '/tmp/' . md5($remoteFile);
            if (!file_exists($tmpFile)) {
                file_put_contents($tmpFile, file_get_contents($remoteFile));
            }
            $attachment = new YouTrack\Attachment();
            $attachment->setUrl($tmpFile);
            $attachment->setName($att['filename']);
            $result = $youtrack->createAttachmentFromAttachment($issue->getId(), $attachment);
            if ($result) {
                unlink($tmpFile);
            }
        }
    }
}
```
With 2000 tickets, i think this should not be a problem. I've moved a lot more tickets in the past. Okay... it depends on the attachments file size.

With a bit of error-handling and marking tickets as imported, this should work.

**Comment by umahanov** [comment]
An API request should always include the `Authorization: Bearer _access_token` header or `X-Api-key: _api_key` and `X-Api-secret: _api_secret` pair in request HTTP headers list.

Example of valid API requests using cURL utility:

`$ curl -H "Authorization: Bearer 94c70d470e391bdc16a8d8363b5d4891" https://api.assembla.com/v1/path/to/resource.json`

Token is not set as `GET` parameters. It is request header. 

Ok, I'll save it to local pc. I just thought there is a way to avoid it

**Comment by nepda** [comment]
Okay, as far as I can imagine, there is no way of moving the files directly between the YouTrack and Assembla server.

Good luck and feel free to open new tickets, if you have any problems with this YouTrack client library ;)

**Comment by umahanov** [comment]
Ok, thank you
