### ISSUE TITLE
updateIssue method

### ISSUE THREAD

**Issue by umahanov** [nepda/youtrack-client#41]
Hi. 

I'm trying to use:

`    public function updateIssue($id, $summary, $description)
    {
        $r = $this->request(
            'POST',
            '/issue/' . urlencode($id) . '?summary=' . urlencode($summary) . '&description=' . urlencode($description)
        );
        return $r['content'];
    }`

The problem is 414 error code, because request is too long. This happens, because description text is too long to be sent as `$GET` parameter.  

I'm just letting you know about this problem (maybe YouTrack problem).  I think, I need to use `executeCommand` method for that case.

**Comment by nepda** [comment]
Thanks... fix is in progress.

**Comment by umahanov** [comment]
Can you please help me, if you have any ideas of how can I update description if it is long and not possible to do it using `updateIssue?` I don't know how to do it using `executeCommand`

The way I try it is:

`$api->executeCommand($issue->getId(), 'description ' . $description);`

Response is 400.

I also tried:

`$api->executeCommand($issue->getId(), 'add description ' . $description);`

**Comment by nepda** [comment]
Please update to version `v1.7.2` (released just now) and try again with `updateIssue`.

**Comment by umahanov** [comment]
Thank you so much for so fast response! This is exactly what I need. It works now.
