### ISSUE TITLE
Import linked issues problem

### ISSUE THREAD

**Issue by umahanov** [nepda/youtrack-client#42]
Hi.
There is a problem using method `importLinks($links)` where `$links` is a collection of elements of `Link `type.

The problem is beneath your magic getters/setter mechanism. 

```
        $link->setTypename(self::$associationTypeNameMap[$ticketAssociation->getRelationship()]);
        $link->setTypeInward(self::$associationTypeInwardMap[$ticketAssociation->getRelationship()]);
        $link->setTypeOutward(self::$associationTypeOutwardMap[$ticketAssociation->getRelationship()]);
```
The problem is that this setters create uppercase properties (TypeName, TypeInWard etc.), while  request format is:

`<link typeName="depend" source="CMN-1928" target="CMN-1917"/>`

That is why I receive an error, that required fields are missing.

Solution I found is not to use settter, but set the values directly:

`$link->typeName = "depend";
 $link->source = "ISSUE-ID"
`

But this setters lead to misunderstanding and I think you can fix it or I can do it and create pull request if you don't have a time for it.

**Comment by nepda** [comment]
To be honest, I've never used this function. I've forked the project a few years ago. I guess no one ever used it :)

If I unterstand the method correctly, please try something like the following:
```
<?php
include_once 'config.php';
$youtrack = new YouTrack\Connection(
    YOUTRACK_URL,
    YOUTRACK_USERNAME,
    YOUTRACK_PASSWORD
);

$links = [
    [
        'typeName' => 'depend',
        'source' => 'CMN-1928',
        'target' => 'CMN-1917',
    ],
    [
        'typeName' => 'rescind',
        'source' => 'CMN-1987',
        'target' => 'CMN-1928',
    ],
];

$youtrack->importLinks($links);
```

I've pushed a commit according to this. Please give feedback, if it works ;)
