### ISSUE TITLE
Check if time tracking is enabled for project

### ISSUE THREAD

**Issue by the-JJ** [nepda/youtrack-client#48]
https://www.jetbrains.com/help/youtrack/standalone/2017.2/GET-Time-Tracking-Settings-for-a-Project.html

**Comment by nepda** [comment]
Thanks!
I've made a few small formatting changes. Maybe it would be more generic, if we provide a method like `getTimetrackingSettings` and a returning object with a few properties according to the docs https://www.jetbrains.com/help/youtrack/incloud/GET-Time-Tracking-Settings-for-a-Project.html
