### ISSUE TITLE
"Unknown bundle field type"

### ISSUE THREAD

**Issue by andreasciamanna** [nepda/youtrack-client#54]
Out of the blue, I started getting the error in the subject when trying to get all the values of a "Fix versions" field of a given project.

I fear that some recent update in YouTrack (inCloud, in my case) might be the cause.

Funny enough, it looks like the not working API was added by my here: 34

Is there any other way to get all the values of a multivalue version field?

I've tried with `\YouTrack\Connection::getVersions` but this causes another error:

>  Error for 'https://<undisclosed>.myjetbrains.com/youtrack/rest/admin/proje  
>  ct/<undisclosed>/version?showReleased=true': 404: Not Found    

Notice that ´https://<undisclosed>.myjetbrains.com/youtrack/rest/admin/project/<undisclosed>´ does return a single node XML with a few details of the project.

**Comment by shane-smith** [comment]
I stopped using YouTrack as it didn't serve my needs, but I have the API code pulled down somewhere. If you can't resolve it in a few days I could try to reproduce on my end.

**Comment by andreasciamanna** [comment]
It was an issue on YouTrack's side: they've released an update with a bug. They fixed it today.

Thanks anyway.
