### ISSUE TITLE
 the parameter sorting has changed

### ISSUE THREAD

**Issue by amehrshad** [nepda/youtrack-client#55]
with new version of Youtrack, the parameter sorting has changed.
For example, at getIssues : 
new version => GET /rest/issue/byproject/{project}?{filter}&{after}&{max}&{updatedAfter}&{wikifyDescription}

**Comment by nepda** [comment]
Which method of this library are you using?

The method `getIssue` still works for me with the YouTrack InCloud version `2018.4 Build 49852`.

`getIssueByProject` is not implemented yet.
https://www.jetbrains.com/help/youtrack/incloud/Get-Issues-in-a-Project.html

I'm using the https://www.jetbrains.com/help/youtrack/incloud/Get-an-Issue.html API description.

**Comment by nepda** [comment]
The old URL endpoint was used in `getIssues`. Also mentioned in #60. This will be fixed with the next release.

**Comment by nepda** [comment]
It's released now. Feel free to report any other bugs or changes.
