### ISSUE TITLE
createComment function is not running

### ISSUE THREAD

**Issue by tamert** [nepda/youtrack-client#56]
Hello, 

I have a problem last at week. my users do not created new comment. 

$youtrack->createComment($issue->id, $_POST['message']);

"Error for 'https://***.myjetbrains.com/youtrack/rest/issue/***-3/execute': 400: Command [] is invalid:Unknown command: Unknown command"

**Comment by nepda** [comment]
This will be fixed with the next release.

**Comment by nepda** [comment]
It's released now. Feel free to report any other bugs or changes.
