### ISSUE TITLE
Login cookies not saved

### ISSUE THREAD

**Issue by nnrudakov** [nepda/youtrack-client#57]
Cookies are checking in case-sensitive [reqexp](https://github.com/nepda/youtrack-client/blob/master/YouTrack/Connection.php#L232) after successful login. YouTrack returns `You are not logged in` on every request then. YouTrack send cookies in lower case now.

When I tried to add an `i` modifier to regexp then requests are working again.

**Comment by nepda** [comment]
I've added the `i` modifier to the regex. It will be in the next release.

If it is possible for you, please use the token-based login.

**Comment by nepda** [comment]
It's released now. Feel free to report any other bugs or changes.
