### ISSUE TITLE
YouTrack 2019.1 support

### ISSUE THREAD

**Issue by xf-** [nepda/youtrack-client#60]
It looks like some functions are broken:

**Projects**
```php
$projetcs = $youtrack->getAccessibleProjects(true);

foreach ($projetcs as $project) {
    var_dump($project->getId());
}
```
Returns `NULL` for all Projects. $project->getName() works

**Issue**
```php
$issue = $youtrack->getIssues("SSG", '#Unresolved');
```

PHP Fatal error:  Uncaught YouTrack\NotFoundException: Error for 'https://domain.tld/yt/rest/project/issues/SSG?max=10&filter=%23Unresolved': 404: Not Found in 

But getIssuesByFilter works.

**Comment by nepda** [comment]
Seems like the property `id` does not exists anymore.
Is it possible to use `shortName` in your case?

The second issue is caused by URL endpoint changes by YouTrack. This will be fixed in the next release.

**Comment by nepda** [comment]
It's released now. Feel free to report any other bugs or changes.

**Comment by xf-** [comment]
@nepda i started with your examples to getId. I switched to `name` afterwards

**Comment by nepda** [comment]
`shortName` is the new `id`.
